In [3]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [5]:
pd.__version__

'2.2.2'

In [8]:
# Lendo um csv
df = pd.read_csv("/content/data_frame_sintetico.csv")

In [11]:
# Lendo um excel
df_1 = pd.read_excel("/content/data_frame_sintetico.xlsx")

In [12]:
# Sanvando um Data Frame

dados = {
    "nomes": ["Marcos", "João", "José", "Marteus"],
    "idades": [20, 25, 22, 23]
}

df_teste = pd.DataFrame(dados)

In [ ]:
# Salvando um DataFrame

In [9]:
df.head()

      ids                                         residencia  doenca
0  vUt43c           8051 Moore Tunnel\nEast Andrea, ND 68017       1
1  658QXL  13766 Catherine Groves Suite 099\nEast Mary, U...       0
2  l50144   6085 Pamela Heights\nPort Raymondmouth, MH 67830       0
3  137VqZ  86416 Hill Terrace Apt. 553\nWest Matthew, MT ...       0
4  W06Vg6    2570 James Streets Apt. 620\nNew Alex, PR 40336       1

In [13]:
df.tail()

        ids                                         residencia  doenca
995  l5C497    54083 Scott Hills\nWest Alexanderport, CO 53390       0
996  46878I          40908 Kevin Crescent\nLake Jodi, WI 19880       0
997  rSpH0T                   PSC 7950, Box 7770\nAPO AP 03720       1
998  06c0n6  7039 Chelsea Valleys Suite 085\nAllisonborough...       1
999  8g00Bl            2093 John Gateway\nNew Cheryl, IN 12794       1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ids         1000 non-null   object
 1   residencia  1000 non-null   object
 2   doenca      1000 non-null   int64
dtypes: int64(1), object(2)
memory usage: 23.6+ KB

In [15]:
# Informações estatísticas

df.describe()

            doenca
count  1000.000000
mean      0.508000
std       0.500186
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [16]:
df.columns

Index(['ids', 'residencia', 'doenca'], dtype='object')

In [17]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [18]:
# Acessando uma coluna específica

df["ids"]

0      vUt43c
1      658QXL
2      l50144
3      137VqZ
4      W06Vg6
        ...
995    l5C497
996    46878I
997    rSpH0T
998    06c0n6
999    8g00Bl
Name: ids, Length: 1000, dtype: object

In [21]:
# Atribuindo os valores de uma coluna a uma tupla

tupla_ids = tuple(df["ids"])
print(tupla_ids[0: 5])

('vUt43c', '658QXL', 'l50144', '137VqZ', 'W06Vg6')

In [22]:
df.columns

Index(['ids', 'residencia', 'doenca'], dtype='object')

In [25]:
# Referênciando mais de uma coluna ao mesmo tempo.

ids_residencia = df[["ids", "residencia"]]
ids_residencia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ids         1000 non-null   object
 1   residencia  1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [26]:
# Acessando linhas pelo índice

df.iloc[100]

ids                                                      77kfON
residencia    8438 Zuniga Falls Suite 273\nNorth Natalie, KS...
doenca                                                        0
Name: 100, dtype: object

In [29]:
# Uma row como lista ou tupla

row_1 = list(df.iloc[100])
print(row_1)

['77kfON', '8438 Zuniga Falls Suite 273\nNorth Natalie, KS 44982', np.int64(0)]

In [33]:
# Acessando a linha e o valor referente a coluna

df.iloc[50]["residencia"]

'054 Shirley Bridge Apt. 429\nMaryland, KS 81033'

In [34]:
from datetime import datetime, timedelta

In [39]:
datetime.now() - timedelta(10)

datetime.datetime(2026, 5, 1, 0, 41, 2, 996344)

In [40]:
def gerar_datetime(data):
  hoje = datetime.now()

  return hoje - timedelta(data)

In [42]:
# Gerando um Datetime

df["data_time"] = [gerar_datetime(dias) for dias in range(1000, 0, -1)]

In [43]:
df.head()

,ids,residencia,doenca,data_time
0,vUt43c,"8051 Moore Tunnel\nEast Andrea, ND 68017",1,2023-08-15 00:41:42.587385
1,658QXL,"13766 Catherine Groves Suite 099\nEast Mary, U...",0,2023-08-16 00:41:42.587395
2,l50144,"6085 Pamela Heights\nPort Raymondmouth, MH 67830",0,2023-08-17 00:41:42.587396
3,137VqZ,"86416 Hill Terrace Apt. 553\nWest Matthew, MT ...",0,2023-08-18 00:41:42.587397
4,W06Vg6,"2570 James Streets Apt. 620\nNew Alex, PR 40336",1,2023-08-19 00:41:42.587398

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ids         1000 non-null   object
 1   residencia  1000 non-null   object
 2   doenca      1000 non-null   int64
 3   data_time   1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 31.4+ KB

In [ ]:
# Passando um data string para o formato DataFrame

df["data_timestamp"] = pd.to_datetime(df["data_timestamp"], format= '%Y-%m-%d')

In [46]:
import random

In [47]:
# Filtrando Dados

df["doses_vacina"] = [random.randint(0, 5) for a in range(1000)]

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ids           1000 non-null   object
 1   residencia    1000 non-null   object
 2   doenca        1000 non-null   int64
 3   data_time     1000 non-null   datetime64[ns]
 4   doses_vacina  1000 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 39.2+ KB

In [50]:
# Pessoas que tomaram mais de uma dose de vacina

df[df["doses_vacina"] > 1]

,ids,residencia,doenca,data_time,doses_vacina
0,vUt43c,"8051 Moore Tunnel\nEast Andrea, ND 68017",1,2023-08-15 00:41:42.587385,5
2,l50144,"6085 Pamela Heights\nPort Raymondmouth, MH 67830",0,2023-08-17 00:41:42.587396,2
5,2975v2,"4146 Carlson Fort Apt. 107\nPort Zachary, PR 9...",1,2023-08-20 00:41:42.587400,3
6,60X6Ij,"987 Julia Hollow Apt. 886\nBradyfort, ID 79383",1,2023-08-21 00:41:42.587401,4
7,Wm8M3D,"PSC 1698, Box 8468\nAPO AE 17266",1,2023-08-22 00:41:42.587402,3
...,...,...,...,...,...
993,58743c,"93566 Jose Dam\nWest Edward, AL 16485",1,2026-05-04 00:41:42.588441,5
995,l5C497,"54083 Scott Hills\nWest Alexanderport, CO 53390",0,2026-05-06 00:41:42.588444,2
996,46878I,"40908 Kevin Crescent\nLake Jodi, WI 19880",0,2026-05-07 00:41:42.588446,2
998,06c0n6,7039 Chelsea Valleys Suite 085\nAllisonborough...,1,2026-05-09 00:41:42.588449,2
999,8g00Bl,"2093 John Gateway\nNew Cheryl, IN 12794",1,2026-05-10 00:41:42.588450,4

In [51]:
# Pessoas que tomaram mais de uma dose de vacina
# nos últimos dos anos

filtro = df[(df["doses_vacina"] > 1) & (df["data_time"].dt.year >=  2025) ]

In [52]:
filtro.head()

,ids,residencia,doenca,data_time,doses_vacina
506,ed9378,"737 Jennifer Cliff Suite 542\nNew Abigail, CA ...",0,2025-01-02 00:41:42.587954,5
507,17mKP0,"825 Johnson Cliffs Suite 844\nJohnport, SC 11323",1,2025-01-03 00:41:42.587955,4
508,0192i7,"48511 Susan Valley\nVincentshire, MO 73253",1,2025-01-04 00:41:42.587956,3
509,EbjL6Y,"5166 Cruz Forge Apt. 945\nWest Jaclyn, SD 47599",0,2025-01-05 00:41:42.587957,4
511,tC0B41,"861 Michael Expressway\nWhitebury, MI 01131",1,2025-01-07 00:41:42.587959,4

In [54]:
filtro_2 = df[(df["doenca"] != 0) | (df["doses_vacina"] > 1)]

In [56]:
filtro_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 828 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ids           828 non-null    object
 1   residencia    828 non-null    object
 2   doenca        828 non-null    int64
 3   data_time     828 non-null    datetime64[ns]
 4   doses_vacina  828 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 38.8+ KB